export const FETCH_FILTERS_REQUEST = 'mutation/FETCH_FILTERS_REQUEST';
export const FETCH_FILTERS_SUCCESS = 'mutation/FETCH_FILTERS_SUCCESS';
export const FETCH_FILTERS_FAILURE = 'mutation/FETCH_FILTERS_FAILURE';

export const GET_ACTIVE_FILTERS_STATE = 'getter/GET_ACTIVE_FILTERS_STATE';
export const GET_ORDERING_STATE = 'getter/GET_ORDERING_STATE';

export const CHANGE_SEARCH_STATE = 'action/CHANGE_SEARCH_STATE';
export const ADD_TO_ACTIVE_FILTERS = 'action/ADD_TO_ACTIVE_FILTERS';
export const REMOVE_FROM_ACTIVE_FILTERS = 'action/REMOVE_FROM_ACTIVE_FILTERS';
export const CLEAR_ACTIVE_FILTERS = 'action/CLEAR_ACTIVE_FILTERS';
export const CHANGE_ORDERING_STATE = 'action/CHANGE_ORDERING_STATE';

export const CHANGE_SEARCH_STATE_MUTATION = 'mutation/CHANGE_SEARCH_STATE_MUTATION';
export const ADD_TO_ACTIVE_FILTERS_MUTATION = 'mutation/ADD_TO_ACTIVE_FILTERS_MUTATION';
export const UPDATE_ACTIVE_FILTERS_MUTATION = 'mutation/UPDATE_ACTIVE_FILTERS_MUTATION';
export const REMOVE_FROM_ACTIVE_FILTERS_MUTATION = 'mutation/REMOVE_FROM_ACTIVE_FILTERS_MUTATION';
export const CLEAR_ACTIVE_FILTERS_MUTATION = 'mutation/CLEAR_ACTIVE_FILTERS_MUTATION';
export const CHANGE_ORDERING_STATE_MUTATION = 'mutation/CHANGE_ORDERING_STATE_MUTATION';
