export const FETCH_CANDIDATES_LIST_REQUEST = 'FETCH_CANDIDATES_LIST_REQUEST';
export const FETCH_CANDIDATES_LIST_SUCCESS = 'FETCH_CANDIDATES_LIST_SUCCESS';
export const FETCH_CANDIDATES_LIST_FAILURE = 'FETCH_CANDIDATES_LIST_FAILURE';

/* Saved candidates consts start */
export const FETCH_SAVED_CANDIDATES_LIST_REQUEST = 'action/FETCH_SAVED_CANDIDATES_LIST_REQUEST';

export const SAVE_CANDIDATE_REQUEST = 'action/SAVE_CANDIDATE_REQUEST';
export const DELETE_SAVED_CANDIDATE_REQUEST = 'action/DELETE_SAVED_CANDIDATE_REQUEST';
/* Saved candidates consts end */

export const CLEAR_CANDIDATES_PAGE = 'CLEAR_CANDIDATES_PAGE';

export const CHANGE_CANDIDATE_REQUEST = 'mutation/CHANGE_CANDIDATE_REQUEST';
export const CHANGE_CANDIDATE_SUCCESS = 'mutation/CHANGE_CANDIDATE_SUCCESS';
export const CHANGE_CANDIDATE_FAILURE = 'mutation/CHANGE_CANDIDATE_FAILURE';
export const CLEAR_CANDIDATE = 'action/CLEAR_CANDIDATE';
export const DELETE_CANDIDATE_AFTER_UNMOUNT = 'mutation/DELETE_CANDIDATE_AFTER_UNMOUNT';
/* Candidate detail consts end */

export const FIND_CANDIDATES_AND_CHANGE_ROUTE = 'action/FIND_CANDIDATES_AND_CHANGE_ROUTE';
export const IS_USER_ACCOUNT_APPROVED = 'getter/IS_USER_ACCOUNT_APPROVED';
